### ISSUE TITLE
Name of library causes inconsistency problems

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Typing#10]
This library is imported by `import circuitpython_typing`, which causes some issues, because the "circuitpython" prefix is often dropped for other libraries.

We could change it to `import typing_circuitpython`, and rename the repo to `Adafruit_CircuitPython_Typing_CircuitPython`, which is a mouthful, but would make its naming scheme consistent.

 See discussion in #9.

**Comment by tekktrik** [comment]
Could we do something like `Adafruit_CircuitPython_CPYTyping` and have it be `cpy_typing` or `adafruit_cpytyping`?

**Comment by tekktrik** [comment]
Or `cirpy` if `cpy` sounds too much like CPython

**Comment by dhalbert** [comment]
This does not seem to be a continuing annoyance, so I'll close this.
