### ISSUE TITLE
docs badge leads to 404

### ISSUE THREAD

**Issue by 2bndy5** [adafruit/Adafruit_CircuitPython_Typing#16]
I found that the docs badge leads to https://docs.circuitpython.org/projects/typing/en/latest/ but I think the proper target is https://docs.circuitpython.org/projects/adafruit-circuitpython-typing/en/latest/

**Comment by tekktrik** [comment]
Good catch!  Want to submit a PR to fix it?

**Comment by 2bndy5** [comment]
It also pretty common for admins to put the docs link in the repo's "About" section. RTD offers a short url for this also.
![image](https://user-images.githubusercontent.com/14963867/169629150-c57faff6-b6ce-4655-aa7f-fd95f83a796c.png)

**Comment by tekktrik** [comment]
Looks like there's a link below that, so between that and the README link that should be good for now.  Thanks for the quick fix!
