### ISSUE TITLE
requirements.txt is missing Adafruit Blinka

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_Typing#23]
This library is missing Adafruit Blinka in it's `requirements.txt`,  It can be fixed by add `Adafruit-Blinka` to the file similar to most other CircuitPython libraries.

**Comment by tekktrik** [comment]
Resolved by #24

**Comment by alexvorobiev** [comment]
Doesn't this create a circular dependency? Adafruit-Blinka depends on this library https://github.com/adafruit/Adafruit_Blinka/blob/main/requirements.txt#L10.

**Comment by tekktrik** [comment]
No, it just means when one library is installed, the other should be as well.  Technically this library doesn't DEPEND on Blinka so much as exist entirely to support it.  Like the other libraries, if someone is downloading this library, it's fair to assume that we should also expect to need Blinka as well.

**Comment by tekktrik** [comment]
On the other hand, you are correct in the Blinka does need (I believe it's a need and not a want, at least) to download this library, hence why this is already a dependency there.
