### ISSUE TITLE
Do not do mpy-cross builds of this library.

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Typing#36]
This library is not meant to run on CircuitPython directly. It does need mpy bundles build (they don't work anyway: #34), and now any CI PR build is failing because it's trying to run mpy-cross, but there's some syntax that's not compatible (`def x(a, /):`).

Now that we've factored out the build options, I don't see a way to force mpy-cross builds not to be done. There are parameters to the release actions that let you suppress certain bundles from being built, and those should be used. But there is no corresponding parameter in the build action. If you agree, we could open an appropriate issue in https://github.com/adafruit/circuitpython-build-tools.

@FoamyGuy @tekktrik

**Comment by tekktrik** [comment]
I agree!  I'm out until next week, but can happily work on that issue.

**Comment by tekktrik** [comment]
Actually, can't we just use [the `--ignore` option to the build command](https://github.com/adafruit/circuitpython-build-tools/blob/96888765af9841dbf9fec383a2de8eb47630be1a/circuitpython_build_tools/scripts/build_bundles.py#L282)?

**Comment by dhalbert** [comment]
@tekktrik points out we need to do "ignore" in the bundle build, which we can do with existing functionality, but also need an "ignore"-type thing in `workflows-circuitpython-libs`.

**Comment by dhalbert** [comment]
OK, looks good: https://github.com/adafruit/Adafruit_CircuitPython_Typing/releases/tag/1.10.1 has no bundles. Thanks @tekktrik.
