### ISSUE TITLE
Syntax error with 1.10.2 running on PiOS

### ISSUE THREAD

**Issue by Ricker42** [adafruit/Adafruit_CircuitPython_Typing#44]
I have adafruit-circuitpython-typing version 1.10.2 installed via pip3 on a Raspberry Pi 3B+ running "Raspbian GNU/Linux 10 (buster)".  I did just do "apt-get update" and "apt-get upgrade" today (Nov 12 2024) so I'm at the latest of everything.

I was trying to set up and use an OLED display, but am getting the following error just during the import section:

```
Traceback (most recent call last):
  File "oled_demo.py", line 5, in <module>
    import adafruit_ssd1306
  File "/usr/local/lib/python3.7/dist-packages/adafruit_ssd1306.py", line 17, in <module>
    from adafruit_bus_device import i2c_device, spi_device
  File "/usr/local/lib/python3.7/dist-packages/adafruit_bus_device/i2c_device.py", line 15, in <module>
    from circuitpython_typing import ReadableBuffer, WriteableBuffer
  File "/home/pi/.local/lib/python3.7/site-packages/circuitpython_typing/__init__.py", line 79
    def read(self, count: Optional[int] = None, /) -> Optional[bytes]:
                                                ^
SyntaxError: invalid syntax
```

The code that produces this is
```
# Load needed modules
import board
import digitalio
from PIL import Image, ImageDraw, ImageFont
import adafruit_ssd1306
```

I looked at the referenced ```__init__.py``` and changed lines 79 and 86 to remove ", /" from the def lines, and all the code then works and I can display something.

**Comment by Ricker42** [comment]
Here's what my locally modified code looks like that doesn't produce the error and I can have code that will display on the OLED:
```#    def read(self, count: Optional[int] = None, /) -> Optional[bytes]:
    def read(self, count: Optional[int] = None) -> Optional[bytes]:
        """Read ``count`` bytes from the stream.
        If ``count`` bytes are not immediately available,
        or if the parameter is not specified in the call,
        the outcome is implementation-dependent.
        """

#    def write(self, buf: ReadableBuffer, /) -> Optional[int]:
    def write(self, buf: ReadableBuffer) -> Optional[int]:
        """Write the bytes in ``buf`` to the stream."""
```

**Comment by Ricker42** [comment]
There was a post on reddit a while ago with the same issue, but no valid solution

[How do i fix this syntax error? Using python 3.7 on raspberry pi. This error is in a file from a up to date Adafruit library](https://www.reddit.com/r/learnpython/comments/1ckyfgb/how_do_i_fix_this_syntax_error_using_python_37_on/)

**Comment by dhalbert** [comment]
The 1.10.2 release was withdrawn ("yanked") from pypi for precisely this issue. See #40. Install 1.10.1, or, preferably upgrade your RPi to a newer version of Raspberry Pi OS. You can also install a later version of Python but do _not_ overwrite the system version of Python. Install a local version from the deadsnakes ppa or similar for use by you, and not by the system.

**Comment by Ricker42** [comment]
Thank you @dhalbert , I am still new to Github and didn't know to look at the pull requests.

For anyone else that finds this, here is how I resolved for myself:

sudo pip3 uninstall adafruit-circuitpython-typing
pip3 uninstall adafruit-circuitpython-typing
pip3 install adafruit-circuitpython-typing==1.10.1

The first two commands are because in trying to fix this issue I had ended up installing the module system-wide and just for my user.  The third command is the key one to force the install of the last version without the issue.

**Comment by dhalbert** [comment]
Glad you got it working. I think that once you uninstalled 1.10.2, the next attempt to install, even without `==1.10.1` should have installed that version, because 1.10.3 and above are designated as needing Python 3.8, so it should have installed the highest possible one without that requirement. The problem with 1.10.2, is that it didn't require >= Python 3.8. But all is well now.
